

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import { ThemeProvider } from '@/components/providers/theme-provider'
import NavbarLeadMagnet from '@/components/NavbarLeadMagnet'
import PopUp from '@/components/PopUp'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          < PopUp />
          <NavbarLeadMagnet />
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
